# docker-compose.yml — versão “atual” (Compose v2 já detecta o esquema automaticamente)
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    volumes:
      - ./site:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: login_db
      DB_USER: user
      DB_PASS: pass

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3311:3306"      # deixe só se precisar acessar o DB externamente
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  db_data:
