services:
  php:
    build: .
    expose:              # apenas “mostra” a porta 80 à rede interna/Traefik
      - "80"
    volumes:
      - ./site:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: login_db
      DB_USER: user
      DB_PASS: pass

  mysql:
    image: mysql:8.0
    restart: always
    expose:
      - "3306"           # acessível só para outros containers
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppass"]
      interval: 10s
      retries: 5

volumes:
  db_data:
